---
# This playbook deploys the whole application stack in this site.  

- name: apply common configuration to all nodes
  hosts: all
  user: root
  roles:
    - common

- include: database.yml
- include: gitolite.yml tags=gitolite
- include: redmine.yml
- include: redmine_plugins.yml

# vim: set filetype=yaml sw=2 ts=2 sts=2 expandtab:
