---

- name: deploy Redmine
  hosts: redmine_server
  user: root
  sudo: yes
  sudo_user: root
  vars_files:
    - secret_passwords.yml
  roles:
    - redmine


# vim: set filetype=yaml sw=2 ts=2 sts=2 expandtab:
