---
# install nginx with passenge
# run as sudo redmine_adm

- name: which gem
  shell: which gem

- name: install nginx-passenger prerequisites
  apt: pkg={{ item }} state=present
  sudo_user: root
  with_items:
    - libcurl4-openssl-dev

- name: install rake gem
  gem: name=rake state=latest user_install=no

- name: install builder gem
  gem: name=builder state=latest user_install=no

- name: install passenger gem
  gem: name=passenger state=latest user_install=no
  register: pv_out

- name: get installed ruby version
  shell: rvm current
  register: rvm_current_out
  tags:
    - cf

#- name: get installed passenger version
#  shell: gem list -l passenger | tail -n1 | cut -d "(" -f 2 | cut -d ")" -f 1 | cut -d ',' -f 1
#  register: pv_out
#  tags:
#    - cf

- set_fact: ruby_current={{ rvm_current_out.stdout }} passenger_version={{ pv_out.version }}
  tags:
    - cf

- name: install nginx
  shell: 
    creates={{ nginx_dir }}/sbin/nginx   
    ~/.rvm/gems/{{ ruby_current }}/bin/passenger-install-nginx-module
    --auto-download --prefix={{ nginx_dir }} --auto
  when: not always_reinstall_nginx

- name: (re-)install nginx
  shell: 
    ~/.rvm/gems/{{ ruby_current }}/bin/passenger-install-nginx-module
    --auto-download --prefix={{ nginx_dir }} --auto

- name: setup nginx configuration file
  template: src=nginx.conf.j2 dest={{ nginx_dir }}/conf/nginx.conf

- name: create nginx init script
  template: src=nginx.j2 dest=/etc/init.d/nginx owner=root group=root mode=0755
  sudo_user: root

- name: run nginx on boot
  service: name=nginx enabled=yes
  sudo_user: root

- name: stop nginx if running
  service: name=nginx state=stopped
  sudo_user: root
  ignore_errors: yes

- name: kill leftover nginx
  command: killall -9 nginx
  sudo_user: root
  ignore_errors: yes

- name: start nginx
  service: name=nginx state=started
  sudo_user: root

# vim: set filetype=yaml sw=2 ts=2 sts=2 expandtab:
