---
# preparation tasks for redmine
# run as sudo root

- name: install system packages required for redmine
  apt: pkg={{ item }} state=present
  with_items:
    - imagemagick
    - libmagickwand-dev
    - libxslt1-dev 
    - libxml2-dev

- name: install unzip
  apt: pkg=unzip state=present

- name: install mercurial
  apt: pkg=mercurial state=present

- name: clone redmine repository (2.4-stable)
  hg: repo=https://bitbucket.com/redmine/redmine dest={{ redmine_dir }} version=2.4-stable

- name: set redmine repository permissions
  file: dest={{ redmine_dir }} owner=redmine_adm group=redmine mode=755 recurse=yes state=directory 
  tags: 
    - perms

- name: create directories accessible by webserver / set permissions
  file: path={{ redmine_dir }}/{{ item }} owner=redmine group=redmine_adm mode=2770 recurse=yes state=directory
  with_items:
    - public/plugin_assets
    - log
    - tmp
    - files
  tags:
    - perms

- name: create restart file
  command: touch {{redmine_dir}}/tmp/restart.txt

- name: set permissions for restart file
  file: path={{redmine_dir}}/tmp/restart.txt owner=redmine_adm group=redmine mode=660 state=file

# vim: set filetype=yaml sw=2 ts=2 sts=2 expandtab:
