---
# Installation von Ruby via RVM

- name: Install prerequisites for RVM
  apt: pkg={{ item }} state=present
  with_items:
   - curl
  sudo_user: root
  tags:
    - rvm

- name: Install RVM
  script: roles/redmine/files/rvm-installer stable
  tags: 
    - rvm

- name: create RVM link for redmine
  file: dest={{ redmine_home }}/.rvm src=/home/redmine_adm/.rvm state=link
  sudo_user: redmine
  tags:
    - rvm

- name: Add RVM loading to bashrc for redmine_adm
  lineinfile: dest=~/.bashrc 
    insertbefore='^# If not running interactively' 
    regexp='^source $HOME/.rvm/scripts/rvm'
    line='source $HOME/.rvm/scripts/rvm'
  tags:
    - rvm

- name: Add RVM loading to bashrc for redmine user
  lineinfile: dest=~/.bashrc 
    insertbefore='^# If not running interactively' 
    regexp='^source $HOME/.rvm/scripts/rvm'
    line='source $HOME/.rvm/scripts/rvm'
  sudo_user: redmine
  tags:
    - rvm

- name: which rvm?
  shell: "which rvm"
  tags:
   - whichrvm

- name: Install Ruby
  shell: rvm install 2.0.0
  tags:
    - ruby

- name: set ruby 2.0 as default for redmine_adm
  shell: rvm alias create default 2.0.0
  tags:
    - ruby

# vim: set filetype=yaml sw=2 ts=2 sts=2 expandtab:
