---
- name: set plugin dir (my_projects)
  set_fact: pdir={{ redmine_dir }}/plugins/my_projects

- name: clone plugin repository
  git: repo=https://github.com/peelman/my_projects dest={{ pdir }}
  notify: 
   - fix permissions
   - restart redmine


# vim: set filetype=yaml sw=2 ts=2 sts=2 expandtab:
