---
- name: set plugin dir (redmine_issue_checklist)
  set_fact: pdir={{ redmine_dir }}/plugins/redmine_issue_checklist

- name: get plugin archive
  get_url: dest={{ redmine_dir }}/plugins/ url=http://redminecrm.com/license_manager/4200/redmine_issue_checklist-2_0_5.zip
  register: result

- name: unzip archive
  shell: chdir={{ redmine_dir }}/plugins unzip redmine_issue_checklist-2_0_5.zip
  when: result.changed
  notify:
    - fix permissions
    - run plugin migration
    - restart redmine


# vim: set filetype=yaml sw=2 ts=2 sts=2 expandtab:
