---
- name: set plugin dir (redmine_group_owners)
  set_fact: pdir={{ redmine_dir }}/plugins/redmine_group_owners

- name: clone plugin repository
  git: repo=https://github.com/m-ramizraja/redmine_group_owners dest={{ pdir }}
  notify: 
   - fix permissions
   - restart redmine

- name: apply hack for newer redmine versions
  copy: src=group_owners_patches.rb dest={{ pdir }}/lib/
  notify:
   - restart redmine


# vim: set filetype=yaml sw=2 ts=2 sts=2 expandtab:
