---
# install redmine_hide_emails_by_default plugin
- name: set plugin dir (redmine_etherpad)
  set_fact: pdir={{ redmine_dir }}/plugins/redmine_hide_emails_by_default

- name: clone plugin repository
  git: repo=https://github.com/splendeo/redmine_hide_emails_by_default dest={{ pdir }}
  notify: 
   - fix permissions
   - run plugin migration
   - restart redmine


# vim: set filetype=yaml sw=2 ts=2 sts=2 expandtab:
