---
- name: set plugin dir (redmine_auto_percent)
  set_fact: pdir={{ redmine_dir }}/plugins/redmine_auto_percent

- name: clone plugin repository
  git: repo=https://github.com/escline/redmine-auto-percent dest={{ pdir }}
  notify: 
   - fix permissions
   - restart redmine


# vim: set filetype=yaml sw=2 ts=2 sts=2 expandtab:
