---
- name: set plugin dir (sidebar)
  set_fact: pdir={{ redmine_dir }}/plugins/sidebar

- name: get plugin archive
  get_url: dest={{ redmine_dir }}/plugins/ url=http://projects.andriylesyuk.com/attachments/download/491/sidebar_0.1.1.tar.bz2
  register: result

- name: untar archive
  shell: chdir={{ redmine_dir }}/plugins tar xjf sidebar_0.1.1.tar.bz2
  when: result.changed
  notify:
    - fix permissions
    - run plugin migration
    - restart redmine


# vim: set filetype=yaml sw=2 ts=2 sts=2 expandtab:
