---
# handlers for redmine plugins

- name: run bundle update
  command: chdir={{ redmine_dir }} bundle update

- name: run bundle install 
  command: chdir={{ redmine_dir }} bundle install --without test

- name: fix permissions
  file: dest={{ pdir }} state=directory owner=redmine_adm group=redmine mode=750
  sudo: yes
  sudo_user: root

- name: run plugin migration
  command: chdir={{ redmine_dir }} rake redmine:plugins:migrate RAILS_ENV=production

- name: restart nginx
  sudo: yes
  sudo_user: root
  service: name=nginx state=restarted

- name: restart redmine
  command: touch /srv/redmine/redmine/tmp/restart.txt


# vim: set filetype=yaml sw=2 ts=2 sts=2 expandtab:
