---
# Dieses Playbook installiert den PostgreSQL-Server und initialisiert den Redmine-DB-Benutzer sowie die DB

- name: Install Postgres server and additional packages
  apt: pkg={{ item }} state=present
  with_items:
   - postgresql-9.1 
   - postgresql-contrib-9.1 
   - postgresql-server-dev-9.1

- name: Start Postgres service
  service: name=postgresql state=started enabled=true

- name: Install python-psycopg2
  apt: pkg=python-psycopg2 state=present

- name: Create Redmine DB User
  sudo: yes
  sudo_user: postgres
  postgresql_user: name={{ redmine_db_user }} password={{ redmine_db_pass }} state=present

- name: Create Redmine Database
  sudo: yes
  sudo_user: postgres
  postgresql_db: name={{ redmine_db_name }} owner={{ redmine_db_user }} encoding=UTF8 template=template0 state=present

