---
# Handler for the redmine server: handlers are called by other plays.

- name: restart nginx
  sudo: yes
  sudo_user: root
  service: name=nginx state=restarted

- name: restart redmine
  command: touch /srv/redmine/redmine/tmp/restart.txt


# vim: set filetype=yaml sw=2 ts=2 sts=2 expandtab:
