---
# install redmine base
# run as sudo redmine_adm

- name: create database config file
  template: src=database.yml.j2 dest={{ redmine_dir }}/config/database.yml group=redmine mode=640
  notify:
    - restart redmine

- name: check if a production config template is provided
  local_action: stat path=roles/redmine/templates/config_production.yml.j2
  sudo: no
  register: config_production
  tags: 
    - redmine_configuration

- name: create configuration.yml.d directory
  file: path={{ redmine_dir }}/config/configuration.yml.d state=directory
  when: config_production.stat.exists
  tags: 
    - redmine_configuration

- name: create configuration.yml header
  template: src=config_header.yml.j2 dest={{ redmine_dir }}/config/configuration.yml.d/config_header.yml
  when: config_production.stat.exists
  tags: 
    - redmine_configuration

- name: create configuration_production file
  template: src=config_production.yml.j2 dest={{ redmine_dir }}/config/configuration.yml.d/config_production.yml
  when: config_production.stat.exists
  tags: 
    - redmine_configuration

- name: assemble configuration.yml
  assemble: remote_src=yes mode=0640
    src={{ redmine_dir }}/config/configuration.yml.d/
    dest={{ redmine_dir }}/config/configuration.yml
  when: config_production.stat.exists
  notify: 
    - restart redmine
  tags: 
    - redmine_configuration

- name: run redmine bundle update
  command: chdir={{ redmine_dir }} bundle update
  notify:
    - restart redmine

- name: run redmine bundle install 
  command: chdir={{ redmine_dir }} bundle install --without test
  notify:
    - restart redmine

- name: generate secret rails token
  command: chdir={{ redmine_dir }} rake generate_secret_token RAILS_ENV=production

- name: migrate database
  command: chdir={{ redmine_dir }} rake db:migrate RAILS_ENV=production
  notify:
    - restart redmine

- name: load default data
  command: chdir={{ redmine_dir }} 
    rake redmine:load_default_data REDMINE_LANG=de RAILS_ENV=production
  notify:
    - restart redmine

- name: fix log permissions
  file: name={{ redmine_dir }}/log/production.log owner=redmine state=file group=redmine_adm mode=0660 
  sudo_user: root
  tags:
    - perms
  notify:
    - restart redmine


# vim: set filetype=yaml sw=2 ts=2 sts=2 expandtab:

