---
# setup git user first and install gitolite for that user

- name: create git user
  user: name=git shell=/bin/bash state=present home={{ git_home }}

- name: prepare .ssh dir
  file: path={{ git_home }}/.ssh/ owner=git group=git state=directory

- include: gitolite.yml
  sudo: yes
  sudo_user: git

- include: git-daemon.yml


# vim: set filetype=yaml sw=2 ts=2 sts=2 expandtab:
