
---
- name: set plugin dir (autowatch)
  set_fact: pdir={{ redmine_dir }}/plugins/autowatch

- name: clone plugin repository
  git: repo=https://github.com/PiratenBayernIT/Redmine-AutoWatch dest={{ pdir }}
  notify: 
   - fix permissions
   - restart redmine


# vim: set filetype=yaml sw=2 ts=2 sts=2 expandtab:
