---
- name: set plugin dir (extended_fields)
  set_fact: pdir={{ redmine_dir }}/plugins/extended_fields

- name: get plugin archive
  get_url: dest={{ redmine_dir }}/plugins/ url=http://projects.andriylesyuk.com/attachments/download/480/extended_fields-0.2.2.tar.bz2
  register: result

- name: untar archive
  shell: chdir={{ redmine_dir }}/plugins tar xjf extended_fields-0.2.2.tar.bz2
  when: result.changed
  notify:
    - fix permissions
    - run plugin migration
    - restart redmine


# vim: set filetype=yaml sw=2 ts=2 sts=2 expandtab:
