# install some redmine plugins. Separate plugins can be installed by specifying their names as tags.
---
- include: redmine_git_hosting.yml tags=redmine_git_hosting
- include: redmine_dmsf.yml tags=redmine_dmsf
- include: redmine_didyoumean.yml tags=redmine_didyoumean
- include: redmine_stealth.yml tags=redmine_stealth
- include: redmine_auto_percent.yml tags=redmine_auto_percent
- include: redmine_issue_checklist.yml tags=redmine_issue_checklist
- include: redmine_mylyn_connector.yml tags=redmine_mylyn_connector


# vim: set filetype=yaml sw=2 ts=2 sts=2 expandtab:
