---
- name: set plugin dir (redmine_per_project_formatting)
  set_fact: pdir={{ redmine_dir }}/plugins/redmine_per_project_formatting

- name: clone plugin repository
  git: repo=https://github.com/a-ono/redmine_per_project_formatting dest={{ pdir }}
  notify: 
   - fix permissions
   - run plugin migration
   - restart redmine


# vim: set filetype=yaml sw=2 ts=2 sts=2 expandtab:
