---
- name: set plugin dir (redmine_equipment_status_viewer)
  set_fact: pdir={{ redmine_dir }}/plugins/redmine_equipment_status_viewer

- name: clone plugin repository
  git: repo=https://github.com/sukima/redmine_equipment_status_viewer dest={{ pdir }}
  notify: 
   - fix permissions
   - run bundle update
   - run bundle install
   - run plugin migration
   - restart redmine


# vim: set filetype=yaml sw=2 ts=2 sts=2 expandtab:
