---
- name: set plugin dir (redmine_startpage)
  set_fact: pdir={{ redmine_dir }}/plugins/redmine_startpage

- name: clone plugin repository
  git: repo=https://github.com/txinto/redmine_startpage dest={{ pdir }}
  notify: 
   - fix permissions
   - run plugin migration
   - restart redmine


# vim: set filetype=yaml sw=2 ts=2 sts=2 expandtab:
