---
- name: set plugin dir (redmine_stealth)
  set_fact: pdir={{ redmine_dir }}/plugins/redmine_stealth

- name: clone plugin repository
  git: repo=https://github.com/kotashiratsuka/redmine_stealth dest={{ pdir }}
  notify: 
   - fix permissions
   - restart redmine


# vim: set filetype=yaml sw=2 ts=2 sts=2 expandtab:
