---
# template for a simple redmine plugin. 
- name: set plugin dir (redmine_example_plugin)
  set_fact: pdir={{ redmine_dir }}/plugins/redmine_example_plugin

- name: clone plugin repository
  git: repo=https://github.com/test/redmine_example_plugin dest={{ pdir }}
  notify: 
   - fix permissions
   - restart redmine


# vim: set filetype=yaml sw=2 ts=2 sts=2 expandtab:
