---
- name: set plugin dir (redmine_knowledgebase)
  set_fact: pdir={{ redmine_dir }}/plugins/redmine_knowledgebase

- name: clone plugin repository
  git: repo=https://github.com/alexbevi/redmine_knowledgebase dest={{ pdir }}
  notify: 
   - fix permissions
   - run bundle update
   - run bundle install
   - run plugin migration
   - restart redmine


# vim: set filetype=yaml sw=2 ts=2 sts=2 expandtab:
